language: ruby
env:
  - ARUBA_TIMEOUT=240
before_install:
  - gem update --system
  - gem update bundler
  - gem cleanup bundler
cache: bundler
rvm:
  - 2.3
  - 2.4
  - 2.5.1
  - ruby-head
branches:
  only:
    - master
install:
  - "bundle install --retry 3 --jobs 8"
gemfile:
  - gemfiles/rails4.2.gemfile
  - gemfiles/rails5.0.gemfile
  - gemfiles/rails5.1.gemfile
  - gemfiles/rails5.2.gemfile
matrix:
  fast_finish: true
  allow_failures:
    - rvm: ruby-head
